const a=10;
const b=2.5;
// const c=a-b;
console.log(a / b);
// alert('Good');
// const shouldRenew = confirm('dbqlb hjp,sqybre');
// console.log(shouldRenew);
// let quantiy = prompt('dbqlb hjp,sqybre');
// quantiy = prompt(quantiy);
// console.log(quantiy);
// console.log(typeof quantiy);
// console.log(typeof '');